# Generated by Django 6.0.5 on 2026-05-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('team1', 'Team1'), ('team2', 'Team2'), ('team3', 'Team3'), ('member', 'Member')], max_length=20)),
            ],
        ),
    ]
