# Generated by Django 5.1.4 on 2026-05-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberlogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('team1', 'Team1'), ('team2', 'Team2'), ('team3', 'Team3'), ('mem', 'Mem'), ('mem2', 'Mem2'), ('mem3', 'Mem3'), ('member', 'Member')], max_length=20),
        ),
    ]
